import { Category, Product, RestaurantSettings, Order } from "@/types"

export const defaultSettings: RestaurantSettings = {
  name: "La Cocina",
  whatsappNumber: "5210000000000",
  currency: "MXN",
}

export const defaultCategories: Category[] = [
  { id: "1", name: "Starters", icon: "salad" },
  { id: "2", name: "Main Course", icon: "utensils" },
  { id: "3", name: "Burgers", icon: "hamburger" },
  { id: "4", name: "Pizza", icon: "pizza" },
  { id: "5", name: "Drinks", icon: "cup-soda" },
  { id: "6", name: "Desserts", icon: "cake" },
]

export const defaultProducts: Product[] = [
  {
    id: "1",
    name: "Caesar Salad",
    description: "Fresh romaine lettuce with parmesan, croutons and our signature dressing",
    price: 145,
    image: "https://images.unsplash.com/photo-1546793665-c74683f339c1?w=400&h=300&fit=crop",
    categoryId: "1",
    available: true,
  },
  {
    id: "2",
    name: "Bruschetta",
    description: "Toasted bread topped with fresh tomatoes, basil and balsamic glaze",
    price: 95,
    image: "https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?w=400&h=300&fit=crop",
    categoryId: "1",
    available: true,
  },
  {
    id: "3",
    name: "Grilled Salmon",
    description: "Atlantic salmon with lemon butter sauce and seasonal vegetables",
    price: 285,
    image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=400&h=300&fit=crop",
    categoryId: "2",
    available: true,
  },
  {
    id: "4",
    name: "Ribeye Steak",
    description: "12oz prime ribeye with garlic mashed potatoes and asparagus",
    price: 450,
    image: "https://images.unsplash.com/photo-1600891964092-4316c288032e?w=400&h=300&fit=crop",
    categoryId: "2",
    available: true,
  },
  {
    id: "5",
    name: "Classic Burger",
    description: "Angus beef patty with cheddar, lettuce, tomato and special sauce",
    price: 175,
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&h=300&fit=crop",
    categoryId: "3",
    available: true,
  },
  {
    id: "6",
    name: "BBQ Bacon Burger",
    description: "Double patty with crispy bacon, BBQ sauce and onion rings",
    price: 215,
    image: "https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=400&h=300&fit=crop",
    categoryId: "3",
    available: true,
  },
  {
    id: "7",
    name: "Margherita Pizza",
    description: "San Marzano tomatoes, fresh mozzarella and basil",
    price: 195,
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400&h=300&fit=crop",
    categoryId: "4",
    available: true,
  },
  {
    id: "8",
    name: "Pepperoni Pizza",
    description: "Classic pepperoni with mozzarella and our house marinara",
    price: 225,
    image: "https://images.unsplash.com/photo-1628840042765-356cda07504e?w=400&h=300&fit=crop",
    categoryId: "4",
    available: true,
  },
  {
    id: "9",
    name: "Fresh Lemonade",
    description: "Freshly squeezed lemonade with mint",
    price: 55,
    image: "https://images.unsplash.com/photo-1621263764928-df1444c5e859?w=400&h=300&fit=crop",
    categoryId: "5",
    available: true,
  },
  {
    id: "10",
    name: "Iced Coffee",
    description: "Cold brew coffee with your choice of milk",
    price: 65,
    image: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400&h=300&fit=crop",
    categoryId: "5",
    available: true,
  },
  {
    id: "11",
    name: "Chocolate Lava Cake",
    description: "Warm chocolate cake with molten center and vanilla ice cream",
    price: 125,
    image: "https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=400&h=300&fit=crop",
    categoryId: "6",
    available: true,
  },
  {
    id: "12",
    name: "Tiramisu",
    description: "Classic Italian dessert with espresso-soaked ladyfingers",
    price: 115,
    image: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400&h=300&fit=crop",
    categoryId: "6",
    available: true,
  },
]

export const defaultOrders: Order[] = [
  {
    id: "1",
    orderNumber: 1001,
    customerName: "Table 5",
    tableNumber: "5",
    items: [
      { productId: "5", productName: "Classic Burger", quantity: 2, price: 175 },
      { productId: "9", productName: "Fresh Lemonade", quantity: 2, price: 55 },
    ],
    total: 460,
    status: "preparing",
    isPaid: false,
    notes: "No onions on the burgers please",
    createdAt: new Date(Date.now() - 5 * 60000).toISOString(),
  },
  {
    id: "2",
    orderNumber: 1002,
    customerName: "Maria Garcia",
    items: [
      { productId: "7", productName: "Margherita Pizza", quantity: 1, price: 195 },
      { productId: "1", productName: "Caesar Salad", quantity: 1, price: 145 },
      { productId: "10", productName: "Iced Coffee", quantity: 2, price: 65 },
    ],
    total: 470,
    status: "ready",
    isPaid: true,
    createdAt: new Date(Date.now() - 15 * 60000).toISOString(),
  },
  {
    id: "3",
    orderNumber: 1003,
    customerName: "Table 8",
    tableNumber: "8",
    items: [
      { productId: "4", productName: "Ribeye Steak", quantity: 1, price: 450 },
      { productId: "3", productName: "Grilled Salmon", quantity: 1, price: 285 },
      { productId: "2", productName: "Bruschetta", quantity: 1, price: 95 },
    ],
    total: 830,
    status: "preparing",
    isPaid: false,
    notes: "Steak medium-rare, salmon well done",
    createdAt: new Date(Date.now() - 8 * 60000).toISOString(),
  },
  {
    id: "4",
    orderNumber: 1004,
    customerName: "John Smith",
    items: [
      { productId: "6", productName: "BBQ Bacon Burger", quantity: 1, price: 215 },
      { productId: "11", productName: "Chocolate Lava Cake", quantity: 1, price: 125 },
    ],
    total: 340,
    status: "delivered",
    isPaid: true,
    createdAt: new Date(Date.now() - 45 * 60000).toISOString(),
  },
  {
    id: "5",
    orderNumber: 1005,
    customerName: "Table 3",
    tableNumber: "3",
    items: [
      { productId: "8", productName: "Pepperoni Pizza", quantity: 2, price: 225 },
      { productId: "9", productName: "Fresh Lemonade", quantity: 4, price: 55 },
    ],
    total: 670,
    status: "ready",
    isPaid: false,
    createdAt: new Date(Date.now() - 12 * 60000).toISOString(),
  },
]
