import { Category, Product, RestaurantSettings, Order } from "@/types"

export const defaultSettings: RestaurantSettings = {
  name: "La Cocina",
  whatsappNumber: "5210000000000",
  currency: "MXN",
}

export const defaultCategories: Category[] = [
  { id: "1", name: "Entradas", icon: "salad" },
  { id: "2", name: "Platos fuertes", icon: "utensils" },
  { id: "3", name: "Hamburguesas", icon: "hamburger" },
  { id: "4", name: "Pizza", icon: "pizza" },
  { id: "5", name: "Bebidas", icon: "cup-soda" },
  { id: "6", name: "Postres", icon: "cake" },
]

export const defaultProducts: Product[] = [
  {
    id: "1",
    name: "Ensalada Cesar",
    description: "Lechuga fresca con parmesano, crutones y aderezo de la casa",
    price: 145,
    image: "https://images.unsplash.com/photo-1546793665-c74683f339c1?w=400&h=300&fit=crop",
    categoryId: "1",
    available: true,
  },
  {
    id: "2",
    name: "Bruschetta",
    description: "Pan tostado con tomate fresco, albahaca y glaseado balsamico",
    price: 95,
    image: "https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?w=400&h=300&fit=crop",
    categoryId: "1",
    available: true,
  },
  {
    id: "3",
    name: "Salmon a la parrilla",
    description: "Salmon con salsa de mantequilla al limon y verduras de temporada",
    price: 285,
    image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=400&h=300&fit=crop",
    categoryId: "2",
    available: true,
  },
  {
    id: "4",
    name: "Ribeye",
    description: "Ribeye con pure de papa al ajo y esparragos",
    price: 450,
    image: "https://images.unsplash.com/photo-1600891964092-4316c288032e?w=400&h=300&fit=crop",
    categoryId: "2",
    available: true,
  },
  {
    id: "5",
    name: "Hamburguesa clasica",
    description: "Carne Angus con cheddar, lechuga, tomate y salsa especial",
    price: 175,
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&h=300&fit=crop",
    categoryId: "3",
    available: true,
  },
  {
    id: "6",
    name: "Hamburguesa BBQ con tocino",
    description: "Doble carne con tocino crujiente, salsa BBQ y aros de cebolla",
    price: 215,
    image: "https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=400&h=300&fit=crop",
    categoryId: "3",
    available: true,
  },
  {
    id: "7",
    name: "Pizza Margarita",
    description: "Tomate San Marzano, mozzarella fresca y albahaca",
    price: 195,
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400&h=300&fit=crop",
    categoryId: "4",
    available: true,
  },
  {
    id: "8",
    name: "Pizza Pepperoni",
    description: "Pepperoni clasico con mozzarella y marinara de la casa",
    price: 225,
    image: "https://images.unsplash.com/photo-1628840042765-356cda07504e?w=400&h=300&fit=crop",
    categoryId: "4",
    available: true,
  },
  {
    id: "9",
    name: "Limonada fresca",
    description: "Limonada natural con menta",
    price: 55,
    image: "https://images.unsplash.com/photo-1621263764928-df1444c5e859?w=400&h=300&fit=crop",
    categoryId: "5",
    available: true,
  },
  {
    id: "10",
    name: "Cafe frio",
    description: "Cafe cold brew con la leche de tu eleccion",
    price: 65,
    image: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400&h=300&fit=crop",
    categoryId: "5",
    available: true,
  },
  {
    id: "11",
    name: "Pastel de chocolate fundido",
    description: "Pastel tibio de chocolate con centro fundido y helado de vainilla",
    price: 125,
    image: "https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=400&h=300&fit=crop",
    categoryId: "6",
    available: true,
  },
  {
    id: "12",
    name: "Tiramisu",
    description: "Postre italiano clasico con soletas remojadas en espresso",
    price: 115,
    image: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400&h=300&fit=crop",
    categoryId: "6",
    available: true,
  },
]

export const defaultOrders: Order[] = [
  {
    id: "1",
    orderNumber: 1001,
    customerName: "Mesa 5",
    tableNumber: "5",
    items: [
      { productId: "5", productName: "Hamburguesa clasica", quantity: 2, price: 175 },
      { productId: "9", productName: "Limonada fresca", quantity: 2, price: 55 },
    ],
    total: 460,
    status: "preparing",
    isPaid: false,
    notes: "Sin cebolla en las hamburguesas, por favor",
    createdAt: new Date(Date.now() - 5 * 60000).toISOString(),
  },
  {
    id: "2",
    orderNumber: 1002,
    customerName: "Maria Garcia",
    items: [
      { productId: "7", productName: "Pizza Margarita", quantity: 1, price: 195 },
      { productId: "1", productName: "Ensalada Cesar", quantity: 1, price: 145 },
      { productId: "10", productName: "Cafe frio", quantity: 2, price: 65 },
    ],
    total: 470,
    status: "ready",
    isPaid: true,
    createdAt: new Date(Date.now() - 15 * 60000).toISOString(),
  },
  {
    id: "3",
    orderNumber: 1003,
    customerName: "Mesa 8",
    tableNumber: "8",
    items: [
      { productId: "4", productName: "Ribeye", quantity: 1, price: 450 },
      { productId: "3", productName: "Salmon a la parrilla", quantity: 1, price: 285 },
      { productId: "2", productName: "Bruschetta", quantity: 1, price: 95 },
    ],
    total: 830,
    status: "preparing",
    isPaid: false,
    notes: "Ribeye termino medio, salmon bien cocido",
    createdAt: new Date(Date.now() - 8 * 60000).toISOString(),
  },
  {
    id: "4",
    orderNumber: 1004,
    customerName: "Cliente 4",
    items: [
      { productId: "6", productName: "Hamburguesa BBQ con tocino", quantity: 1, price: 215 },
      { productId: "11", productName: "Pastel de chocolate fundido", quantity: 1, price: 125 },
    ],
    total: 340,
    status: "delivered",
    isPaid: true,
    createdAt: new Date(Date.now() - 45 * 60000).toISOString(),
  },
  {
    id: "5",
    orderNumber: 1005,
    customerName: "Mesa 3",
    tableNumber: "3",
    items: [
      { productId: "8", productName: "Pizza Pepperoni", quantity: 2, price: 225 },
      { productId: "9", productName: "Limonada fresca", quantity: 4, price: 55 },
    ],
    total: 670,
    status: "ready",
    isPaid: false,
    createdAt: new Date(Date.now() - 12 * 60000).toISOString(),
  },
]
